version: '3.9'
services:
  app:
    container_name: golang_container
    build: .
    environment:
      - DB_HOST=postgresdb
      - DB_USER=gk
      - DB_PASS=1234
      - DB_NAME=test
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      - backend

  postgresdb:
    image: postgres:14
    container_name: postgres_container
    environment:
      - POSTGRES_USER=gk
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    ports:
      - "5436:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
